"""add monthly fee to players

Revision ID: 162d294b8028
Revises: 
Create Date: 2026-09-28 12:30:39.011817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162d294b8028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('monthly_fee')

    # ### end Alembic commands ###
