"""Add player transfer history

Revision ID: 3ff3d02e948d
Revises: 162d294b8028
Create Date: 2026-10-01 16:18:01.723946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff3d02e948d'
down_revision = '162d294b8028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_category_id', sa.Integer(), nullable=False),
    sa.Column('to_category_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('transferred_by', sa.String(length=120), nullable=True),
    sa.Column('transferred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_transfers_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_transfers_transferred_at'), ['transferred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_transfers_transferred_at'))
        batch_op.drop_index(batch_op.f('ix_player_transfers_player_id'))

    op.drop_table('player_transfers')
    # ### end Alembic commands ###
