"""add player login account relationship

Revision ID: 888d98b1af16
Revises: 3ff3d02e948d
Create Date: 2026-10-08 10:42:38.127720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888d98b1af16'
down_revision = '3ff3d02e948d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
